
 a1edem20
  
  nginx2:
    image: nginx:latest
    ports:
     nginx4:

version: '3.5'
services:

  nginx4:
 main
    image: nginx:latest
    ports:
      - "8004:80"
  nginx5:
    image: nginx:latest
    ports:
      - "8005:80"
  nginx4:
    image: nginx:latest
    ports:
      - "8004:80"
  nginx5:
    image: nginx:latest


  nginx6:
    image: nginx:latest
    ports:
      - "8006:80"
 main
  nginx7:
    image: nginx:latest
    ports:
      - "8007:80"
  nginx8:
    image: nginx:latest
    ports:
      - "8008:80"
  nginx9:
    image: nginx:latest
    ports:
      - "8009:80"

eric configs:
"eric kemvou"